server.ssl.enabled=true
server.ssl.key-store=/opt/radar-saver/ssl/keystore.p12
server.ssl.key-store-password=
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=radar-saver
server.ssl.client-auth=none
server.ssl.enabled-protocols=TLSv1.3,TLSv1.2

management.endpoints.web.exposure.include=health,info,prometheus
