- name: "Setup {{ db_name }} Database"
  gather_facts: no
  vars_files:
    - vars/prod.yml
  hosts: castle
  remote_user: "{{ remote_admin }}"
  tasks:
    - name: "Create database {{ db_name }}"
      become_user: postgres
      become: yes
      postgresql_db:
        state: present
        name: "{{ db_name }}"
        port: "{{ db_port }}"

    - name: "Create db user {{ db_name }}"
      become_user: postgres
      become: yes
      postgresql_user:
        state: present
        name: "{{ db_name }}"
        password: "{{ db_password }}"
        port: "{{ db_port }}"

    - name: "Create schema {{ db_name }}"
      become_user: postgres
      become: yes
      postgresql_schema:
        state: present
        name: "{{ db_name }}"
        owner: "{{ db_name }}"
        login_password: "{{ db_password }}"
        login_port: "{{ db_port }}"
        login_db: "{{ db_name }}"
        comment: 'Radar Event Saver schema'

    - name: "Create schema liquibase"
      become_user: postgres
      become: yes
      postgresql_schema:
        state: present
        name: liquibase
        owner: "{{ db_name }}"
        login_password: "{{ db_password }}"
        login_port: "{{ db_port }}"
        login_db: "{{ db_name }}"
        comment: 'Liquibase schema'

    - name: "Grant db user {{ db_name }} access to app db {{ db_name }}"
      become_user: postgres
      become: yes
      postgresql_privs:
        type: database
        database: "{{ db_name }}"
        roles: "{{ db_name }}"
        grant_option: no
        privs: all
        port: "{{ db_port }}"

    - name: "Start service postgresql"
      become: yes
      systemd:
        name: postgresql
        state: started
